/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.truongvm;

// import com.arrayandhash.ArrayAndHashSolution;

public class App {
  public String getGreeting() {
  return "Hello World!";
  }

  public static void main(String[] args) {
    
    System.out.println(new App().getGreeting());
    // ArrayAndHashSolution test = new ArrayAndHashSolution();
    // System.out.println(test.containsDuplicate(new int[] { 1, 2, 3, 4, 5, 5 }));
  }
}
